name: build-vs

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    if: github.event_name == 'pull_request' && github.repository == 'openframeworks/openFrameworks'
    paths-ignore:
      - '**/*.md'
      - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-vs2019:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - platform: x64
            bits: 64
    env:
      BITS: ${{ matrix.bits }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            unzip
            zip
            rsync
            wget
      - uses: actions/setup-node@v4
        with:
          node-version: 16   
      - name: Install dependencies
        shell: msys2 {0}
        run:
          ./scripts/vs/ci_install.sh
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build projectGenerator
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run:
          msbuild ../openFrameworks/apps/projectGenerator/commandLine/commandLine.vcxproj /p:configuration=release /p:platform=${{ matrix.platform }} /p:PlatformToolset=v142
      - name: Create projectGenerator cmd zip
        if: github.repository == 'openframeworks/projectGenerator' && github.ref == 'refs/heads/master'
        shell: msys2 {0}
        run:
          ./scripts/vs/ci_cmd_package.sh

      - name: Build projectGenerator VS GUI
        shell: msys2 {0}
        run:
          ./scripts/vs/build_frontend.sh
      - name: Create projectGenerator VS GUI package
        shell: msys2 {0}
        run:
          ./scripts/vs/ci_frontend_package.sh
      - name: Update CMD Gen Release
        if: github.repository == 'openframeworks/projectGenerator' && github.ref == 'refs/heads/master'
        uses: IsaacShelton/update-existing-release@v1.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          release: nightly
          prerelease: false
          replace: false
          files: ../openFrameworks/apps/projectGenerator/commandLine/bin/projectGenerator-vs.zip
      - name: Update Project Gen GUI Release
        if: github.repository == 'openframeworks/projectGenerator' && github.ref == 'refs/heads/master'
        uses: IsaacShelton/update-existing-release@v1.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          release: nightly
          prerelease: false
          replace: false
          files: ../openFrameworks/apps/projectGenerator/frontend/dist/rojectGenerator-vs-gui.zip
