name: build-macos

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-osx:
    runs-on: macos-13
    strategy:
      matrix:
        cfg:
          - {target: osx}
    env:
      TARGET: ${{ matrix.cfg.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16       
      - name: rm-dev
        run: sudo rm -rf /Library/Developer
      - name: Setup
        run: ./scripts/osx/setup.sh
      # - name: Build CMDLINE
      #   run: ./scripts/osx/build_cmdline.sh
      # - name: Build frontend
      #   run: ./scripts/osx/build_frontend.sh
      - name: Build
        run: ./scripts/osx/ci_build_pg.sh
        env:
          DEVELOPER_DIR: "/Applications/Xcode_15.0.1.app/Contents/Developer"
          SDKROOT: "/Applications/Xcode_15.0.1.app/Contents/DeveloperPlatforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          GA_APPLE_USERNAME: ${{ secrets.GA_APPLE_USERNAME }}
          GA_APPLE_PASS: ${{ secrets.GA_APPLE_PASS }}
          GA_NOTARIZE_PROVIDER: ${{ secrets.GA_NOTARIZE_PROVIDER }}
      - name: List output directory
        run: ls -lah /
      - name: Update Release
        if: github.repository == 'openframeworks/projectGenerator' && github.ref == 'refs/heads/master'
        uses: IsaacShelton/update-existing-release@v1.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          release: nightly
          prerelease: false
          replace: false
          files: projectGenerator-osx.zip projectGenerator-ios.zip
