name: build-linux

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ccache: ccache
  GA_CI_SECRET: ${{ secrets.CI_SECRET }}

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cfg:
        - {target: linux}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - name: Install libunwind
      run:  sudo apt-get install libunwind-dev
    - uses: actions/checkout@v4
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.12
      with:
        key: ${{ matrix.os }}-${{ matrix.cfg.target }}
    - name: Install
      run:
        ./scripts/linux/ci_install_core.sh
    - name: List directory
      run: ls -lah ./
    - name: Build
      run:
        ./openFrameworks/apps/projectGenerator/scripts/linux/buildPG.sh;
    - name: List output directory
      run: ls -lah openFrameworks/apps/projectGenerator/commandLine/bin
    - name: Test Artefact zip
      run: |
        tar -cjf openFrameworks/apps/projectGenerator/commandLine/bin/artefact.tar.bz2 -C openFrameworks/apps/projectGenerator/commandLine/bin 
    - name: Upload binaries as Artefact
      uses: actions/upload-artifact@v4
      with:
        name: project-Generator-linux
        path: openFrameworks/apps/projectGenerator/commandLine/bin/artefact.tar.bz2
        retention-days: 1
        
